### ISSUE TITLE
Wrong Submit a Ticket Link

### ISSUE THREAD

**Issue by darbin** [ACCORD5/TrellisDesk#10]
When you click "Submit A Ticket" link is index.php?page=tickets&act=open instead of index.php?page=tickets&act=add

**Comment by DanielRuf** [comment]
Are you using the latest version from here? In v2 I can create Tickets and the links is also `index.php?page=tickets&act=add`

**Comment by darbin** [comment]
Yes, I have the latest version. Problem not in a link in a navbar, but in link with letter and a pencil above the "Sample News Item"

**Comment by DanielRuf** [comment]
Well, this is the old skin. In the readme there is written, that we work on the skins later.

In the `skins/s1/templates/dashboard.tpl` change every `act=open` to `act=add` =)  See also the new patch I created =)

**Comment by darbin** [comment]
Thanks KAOSFORGE!
