### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by DanielRuf** [ACCORD5/TrellisDesk#11]
I am reporting currently all errors / issues I see while testing so we can work on them.

Currently:

```
{lang.td_latest_news}
{lang.td_latest_news_msg}
```

and

```
{lang.help_about_settings_title}
{lang.help_about_settings_msg}
```

seem to be not translated / the translations seem to be missing.

**Comment by djtarazona** [comment]
Yes, there are probably a lot of translations missing from the ACP.

**Comment by DanielRuf** [comment]
We should collect the missing strings and see what we can do. Maybe we write some translations and add them to the right files.

**Comment by darbin** [comment]
Also:
{lang.help_about_settings_title}
{lang.help_about_settings_msg}
{lang.help_about_emails_msg}
{lang.help_about_logs_title}
{lang.help_about_logs_msg}
{lang.help_about_cache_title}
{lang.help_about_cache_msg}

**Comment by darbin** [comment]
{lang.tip_upload}
{lang.tip_name_staff}
{lang.tip_abbr_staff}
{lang.tip_name_user}
{lang.tip_abbr_user}
{lang.tip_type}

**Comment by DanielRuf** [comment]
Great. =) I think I will write some translations / localizations tomorrow =)

**Comment by ErenPhayte** [comment]
Any word on these translations?

**Comment by DanielRuf** [comment]
I do not work anymore on this project as I do not get any response by dj tarazona!
