### ISSUE TITLE
Update Skins to look like ACP

### ISSUE THREAD

**Issue by DanielRuf** [ACCORD5/TrellisDesk#13]
The skins look to me very old and unmodern. Also there seem to be some problems on smaller displays with the skins (like smartphones) 

We should use this shiny admin skin everywhere (with css3 maybe and color swatches)

**Comment by djtarazona** [comment]
You're talking in regards to the frontend (client end) correct?  If so, it is definitely in need of an upgrade / new look.

Aaron, the ACCORD5 Creative Director, might be whipping up a new skin for us.  Of course, anyone else can take a crack at it as well!
