### ISSUE TITLE
Better / new Icons?

### ISSUE THREAD

**Issue by DanielRuf** [ACCORD5/TrellisDesk#15]
I found the great icon pack Plastique Icons (CC and GPL?) we can use maybe for some parts.

Also I want to use Trellis in the future more on mobile devices so these icons are perfect for such displays and in general.

**Comment by djtarazona** [comment]
Link? (just to make sure we are on the same page)

I've been quite happy with the icons so far but of course we are always open to suggestions.  Can you please describe the pros / cons of switching the icon set?  Right now I believe we are using Fugue icons.

**Comment by DanielRuf** [comment]
here it is: http://iconify.it/free-stuff/plastique-icons-full-set/

I dont suggest to switch the icons but we need a mobile theme / skin with other / bigger / better icons as I think the current icons are way too small for mobile touch devices

**Comment by djtarazona** [comment]
Agreed.  A mobile theme would be nice.  I would much rather do that than replace the icons.

**Comment by DanielRuf** [comment]
Not replace but use new icons for the mobile theme like plastique.
