### ISSUE TITLE
Link to Admin Panel / ACP when logged in

### ISSUE THREAD

**Issue by DanielRuf** [ACCORD5/TrellisDesk#18]
Seems there is no such link and I have to go manually to /admin.php

**Comment by djtarazona** [comment]
The idea is that admin / staff would never access the frontend and would always enter / bookmark with admin.php.  Do you think it is worth it to add a link from the frontend?

**Comment by DanielRuf** [comment]
Well I think it is definitely. Because the Admin needs it or the Staff. When I personally have many websites and I forget the link and have no bookmark, then I have to try to get the right URL.

Makes it a bit easier to access the backend (for admin / staff)

**Comment by djtarazona** [comment]
I guess it can't hurt to be added in.

**Comment by DanielRuf** [comment]
Can do that next time.
