### ISSUE TITLE
Dont show corresponding buttons if the user has not the right permissions

### ISSUE THREAD

**Issue by DanielRuf** [ACCORD5/TrellisDesk#27]
Tabs and Buttons like Edit, Add, Add Group, Add User ... and so on should not be displayed when the user has not the permission / rights for it. The error "no perm" that is thrown is very ugly and not so userfriendly.

So the user sees directly what he can do and what not and doesnt have to learn by the no perm errors that he cant do specific things.

**Comment by darbin** [comment]
I totally agree. It would be great to make it invisible if user does not have access to see any menu.

**Comment by djtarazona** [comment]
Agreed!

**Comment by fhr2** [comment]
good. I will wait

**Comment by fentontech** [comment]
Wouldnt sessions be an easy way to approach this?

**Comment by DanielRuf** [comment]
Sessions? There are perms who have be checked but the corresponding function is broken see https://github.com/ACCORD5/Trellis-Desk/issues/40

**Comment by djtarazona** [comment]
Ideally, you would check the permissions using the appropriate function and only display the link / button if the user has appropriate access.  Of course, we need to get the perm check working.  I'll tackle that soon unless someone gets to it before me.

**Comment by DanielRuf** [comment]
Thats what I already did. Well good luck with it.
