### ISSUE TITLE
Trellis Desk v2 Roadmap

### ISSUE THREAD

**Issue by DanielRuf** [ACCORD5/TrellisDesk#31]
We should start to make some plans about what to do and setting priorities.
1. Fix missing translations / texts
2. Fix functions / features so they work properly
3. Fix other general problems / errors (missing icons, rights ...)
4. ...

a Gantt Chart would maybe help a lot?

**Comment by djtarazona** [comment]
Where do you propose we setup / implement a Gantt chart?

**Comment by DanielRuf** [comment]
On a gh page. Just setup github pages when you `admin` the repository.

**Comment by djtarazona** [comment]
A GitHub page will generate a Gantt chart?

**Comment by DanielRuf** [comment]
Use gantt or a jquery sceipt to generate it and push it to the gh page branch. Also milestones are good.

**Comment by djtarazona** [comment]
Have you used Asana?  It is amazing.  I'm thinking maybe we can use it to better organize the project.

http://asana.com/

**Comment by DanielRuf** [comment]
Well, here on github there are already organizations and issues, assignees and so on. Also Asana looks like Github. Currently testing it but most of the features are already in Github.

How would you use Asana for this project? Do you have already some plans?

I tried Asana and ts not good for Open Source projects like Trellis Desk (only invitation) and so it is against the ideas behind open source. Not useful for open source and github as there are alread issues, wikis and pages on github.

But good for commercial and not public projects.

**Comment by djtarazona** [comment]
Agreed.  I was a little caught up in the excitement as I am using Asana at work now (for private projects) and I love it.  I also didn't realize you could assign Github issues to people.

@KAOSFORGE lets try to catch each other on Skype soon. Sending you a private message.
