### ISSUE TITLE
Errors in hosting

### ISSUE THREAD

**Issue by darbin** [ACCORD5/TrellisDesk#40]
I just install latest version on hosting and get this errors in upper part of screen (in local hosting everything works fine)

On admin page:
Warning: Call-time pass-by-reference has been deprecated in /includes/classes/class_asession.php on line 155
On main page:
Warning: Call-time pass-by-reference has been deprecated in /includes/classes/class_session.php on line 87
Warning: Call-time pass-by-reference has been deprecated in /includes/classes/class_skin.php on line 240
Warning: Call-time pass-by-reference has been deprecated in //includes/classes/class_skin.php on line 242
Warning: Call-time pass-by-reference has been deprecated in /includes/classes/class_skin.php on line 244
Warning: Call-time pass-by-reference has been deprecated in /includes/classes/class_skin.php on line 250

PHP Version 5.2.17
MySQL Version   5.1.53

**Comment by DanielRuf** [comment]
Which PHP version do you use?  `allow_call_time_pass_reference = Off` should be `ON` in the php.ini on your server?

The  `&` seems to be a problem. Maybe a space behind them in the corresponding lines helps. 

We shoukd change eg `function set_var($key, $value)` to `function set_var($key, &$value)`   

Please see also http://bytes.com/topic/php/answers/759990-call-time-pass-reference-has-been-deprecated 

and other websites about this warning: 

http://www.google.com/search?q=Call-time+pass-by-reference+has+been+deprecated&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:de:official&client=firefox-a&hl=en

I will maybe fix this tomorrow

**Comment by darbin** [comment]
PHP Version 5.2.17
allow_call_time_pass_reference is Off and I don't think my hosting allow me to change this value. I try to set php value through .htaccess using "php_flag allow_call_time_pass_reference 1" but it not works for me.

**Comment by DanielRuf** [comment]
Currently it is just a warning that you can hide with something like `error_reporting` set to off

As I wrote, I will fix this warning in about 14 hours.

**Comment by DanielRuf** [comment]
Did you get also more errors / warnings somewhere?

I tested it on my server here and I get no warnings.

I suggest you test it with a newer PHP version. Yours is very old and unstable.

Also the minimum requirements are:
```    PHP 5.3
    MySQL 4.1
    GD2 + FreeType (for some CAPTCHA support)

```

So please try to get a newer php version. My hoster moves my websites to a newer server with a newer php version if I want it. 
```

**Comment by darbin** [comment]
I upgrade php version to 5.3.5 and problem gone.
Thank you!

**Comment by DanielRuf** [comment]
Well, thanks. It is also suggested to use min. 5.3 =) Glad that you solved it =)
