### ISSUE TITLE
Printing Tickets does not work

### ISSUE THREAD

**Issue by DanielRuf** [ACCORD5/TrellisDesk#45]
The whole function for printing a ticket / tickets is missing.

So a big TODO =)

**Comment by darbin** [comment]
It would be great if it were possible to print the ticket in PDF (and even better if you can make customizable pdf output)

**Comment by DanielRuf** [comment]
There are some great projects here on Github so I will look for a good solution for printing =)

**Comment by DanielRuf** [comment]
Printing HTML Templates (with jquery.print.js) is also a good solution.

Another real good aolution would be http://www.fpdf.org/ for generating pdf files (logs, statistics, tickets ...)

**Comment by djtarazona** [comment]
There is also http://code.google.com/p/dompdf/ which I just used in a recent project.

**Comment by DanielRuf** [comment]
Will take a look at it.
But I think FPDF is more stable, not so betaish and has more features (and is also installed on many web servers as pecl extension?) or the PDFLib of PHP? We should rely on well documented, most used, most stable and secure solutions and use existing ones if we can use them.

**Comment by djtarazona** [comment]
Agreed.
