### ISSUE TITLE
How to make the user to see all the tickets your group?

### ISSUE THREAD

**Issue by fhr2** [ACCORD5/TrellisDesk#47]
How to make the user to see all the tickets your group?
Как сделать чтобы пользователь видел все билеты своей группы?

**Comment by DanielRuf** [comment]
Add the user to the right group 

This is not an issue or a bug / error, or?

Should be added to the documentation / description of groups and permissions

**Comment by fhr2** [comment]
sorry.
How to make a manager who will see only the application of the group without the ability to change system settings?
If you do the personnel - the user sees the entire administration panel, but can not edit the parameters (top tell lies no_perm)

**Comment by DanielRuf** [comment]
You as the admin have to do this for him. Or you give him the rights to access the Admin Control Panel (ACP)

Right, he has no perms if you set them so. You can set the permissions per user / group if he can access the ACP and do specific things there.

If he can acces ACP but has no more rights tom edit and so on then you get this (no error). But the users who can access the ACP, should have also the rights to do somwthing there. All others dont need the right to access the ACP.

**Comment by fhr2** [comment]
to make the user who can see all tickets must give the group access to the ACP?
Other ways to display group tickets as soon as possible?

**Comment by DanielRuf** [comment]
Yes. You have to set the right permissions. I see there no issue or bug.

**Comment by fhr2** [comment]
display disabled menu items is not a mistake?
Tickets only display sheet can not?

**Comment by DanielRuf** [comment]
This is indeed a mistake and there is also already a issue created by me about this.

Please see https://github.com/ACCORD5/TrellisDesk/issues/27
