### ISSUE TITLE
More secure passwords / better encrpytion algorithm

### ISSUE THREAD

**Issue by DanielRuf** [ACCORD5/TrellisDesk#52]
We should use `crypt` or `mcrypt` with the `bcrypt` algorithm maybe use also `http://www.openwall.com/phpass/`

**Comment by djtarazona** [comment]
Agreed.  If we were to change the hashing algorithm, it should be backwards compatible with old passwords so that we don't have to force everyone to reset their passwords.

**Comment by DanielRuf** [comment]
Not change, add. Also they are stronger these encryptions. Old passwords will not be compatible. They have to be generated again. But we could check and fetch the current strings from the database and encrypt them with the new method.
