### ISSUE TITLE
Plans for 2.0, 2.1 and already 3.0

### ISSUE THREAD

**Issue by DanielRuf** [ACCORD5/TrellisDesk#56]
I am planning a totally new and much better Trellis Desk in 3.0.

Also I am working most time at Trellis Desk and push the development with bugfixes, new functions and so on.

Some big changes will come in the future and I need the help of everyone.

Creating issues and working on Trellis Desk on https://github.com/ACCORD5/Trellis-Desk should boost the development.

So please use this link for all new issues and also work with the newest version there. You can also copy some open issues from here to there if you want so I cant work on them better.

Daniel Ruf

**Comment by fentontech** [comment]
The link doesnt work.......

**Comment by DanielRuf** [comment]
fixed

**Comment by DanielRuf** [comment]
Great accord5! For deleting the better repo (with tagged versions, downloads ...) and never answering me!

**Comment by rxt360** [comment]
That link doesn't work. Do you know what the current status is for Trellis? Is there active development from Accord5?

**Comment by DanielRuf** [comment]
Because the deleted this repo which was some commits more. Ask accord5 but do not expect an answer as they never answered me.
