### ISSUE TITLE
some changes to the project

### ISSUE THREAD

**Issue by DanielRuf** [ACCORD5/TrellisDesk#61]
I will clone all current issues and milestones and labels from https://github.com/kaosforge/trellisdesk
That takes a while. You can also subscribe there to the mailing list which will move later to this repo here.

Please test the very last version and post the issues / bugs so we can check this.

**Comment by djtarazona** [comment]
Sounds good.  I've been taking a look at email parsers lately as this is something I really want to handle properly in Trellis Desk 2.  Take a look at:

http://code.google.com/p/php-mime-mail-parser/

Looks pretty promising.  Trellis Desk v1 is using my own parser which is just a mess.  Do you have any other suggestions?

**Comment by DanielRuf** [comment]
Do swiftmailer and other popular scripts not support piping?

There are some more good alternatives we can try.

**Comment by djtarazona** [comment]
I believe SwiftMailer only generates and handles OUTGOING emails.  I doesn't parse incoming.  If it did I would love to use SwiftMailer as it is used for our outgoing emails.
