### ISSUE TITLE
Git Tags?

### ISSUE THREAD

**Issue by bhubbard** [ACCORD5/TrellisDesk#64]
Any reason there are no git tags for versons or alphas, such as 1.0.4  2.0 etc?

**Comment by aarondraczynski** [comment]
When we first pushed Trellis Desk up to GitHub several months ago, the codebase was at 2.0 alpha 4. As development progresses, we'll continue tagging new releases.

**Comment by DanielRuf** [comment]
Hm that is weird. Why did you ignore all my last commits and deleted my fork with all tagged versions, downloads, issues ...  you could change the repos name!   That was a bad idea what you did.

**Comment by bhubbard** [comment]
@Daniel, I assume that comment was directed to aaron?

**Comment by DanielRuf** [comment]
No statement until today? => https://github.com/ACCORD5/TrellisDesk/issues/67

**Comment by DanielRuf** [comment]
hello?
