### ISSUE TITLE
Icons was missing on Trellis Desk Default Skin

### ISSUE THREAD

**Issue by jazarja** [ACCORD5/TrellisDesk#9]
Icon was missing on Trellis Desk Default Skin (.../skins/s1/images/icons/arrow_back.png)

**Comment by darbin** [comment]
There is not just one file missing, but the whole folder icons.

**Comment by djtarazona** [comment]
Added!

**Comment by DanielRuf** [comment]
Will also add them this afternoon to my repo (in about 9-10 hours here)
